### ISSUE TITLE
Documentation doesn't have a DESCRIPTION section

### ISSUE THREAD

**Issue by neilbowers** [racke/Data-Transpose#10]
The documentation doesn't have a DESCRIPTION header at the start of the main body of documentation. Various tools expect that header to mark the start of the descriptive text.

For example, MetaCPAN takes the first N characters of the DESCRIPTION section as the summary of the module, which is displayed in search results. I usually go for a first paragraph like:

    =head1 DESCRIPTION

    This module provides a number of methods for manipulating manipulating Perl objects and data structures. Blah blah blah.

This module was just assigned in the Pull Request challenge, so if you're happy with this being changed, perhaps you could leave it for a PR? :-)

Cheers,
Neil

**Comment by racke** [comment]
Yes, PR would be excellent. Just use the second paragraph of the NAME section as DESCRIPTION.

Thanks
              Racke
